name: smooth_shadow
description: A shadow generator for Flutter.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  hooks_riverpod: ^2.3.6
  google_fonts: ^5.0.0
  url_launcher: ^6.1.11
  dart_mappable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint:
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.5
  dart_mappable_builder: ^3.1.1

flutter:
